sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge GroupE
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network GroupE mongo
  - docker build -t GroupE .
  - docker run --network se-methods GroupE
